config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  constraints subdomain: true do
    devise_for :users
    get '/', to: 'apps#show'
    resources :apps, only: [:update, :destroy]

    namespace :admin do
      get '/settings', :to => "pages#settings"
      get '/javascript', :to => "pages#javascript"
      post '/intercom_settings', :to => "pages#intercom_settings"
      post '/render_settings', :to => "pages#render_settings"
    end
  end

  constraints subdomain: false do
    root to: 'pages#home'
    resources :apps, only: [:index, :new, :create]
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :apps
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :admin

  validates :subdomain, :admin_id, :intercom_id, presence: true
  validates :subdomain, uniqueness: true
  validates :subdomain, :intercom_id, format: { with: /\A[a-z0-9]*\z/, message: ": must use lower-case letter or numbers, without spaces."}
  validates :subdomain, length: {maximum: 20, too_long: ": %{count} characters is the maximum allowed"}
  validates :subdomain, format: { with: /\A[a-z0-9]+\z/ }
  validates :intercom_id, length: {maximum: 50, too_long: ": %{count} characters is the maximum allowed"}
  validates :intercom_id, :uniqueness => {:scope => :admin_id, message: ": You already have a site with that Intercom app id"}
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_tenant(:app)
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  validates_uniqueness_to_tenant :email
  validates_presence_of   :email, if: :email_required?

  validates_presence_of     :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?

  def self.find_for_authentication(warden_conditions)
    where(:email => warden_conditions[:email], :subdomain => warden_conditions[:subdomain]).first
  end

  protected
    # Checks whether a password is needed or not. For validations only.
    # Passwords are always required if it's a new record, or if the password
    # or confirmation are being set somewhere.
    def password_required?
      !persisted? || !password.nil? || !password_confirmation.nil?
    end

    def email_required?
      true
    end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  layout 'admin_layout'
  before_action :authorize
  include ApplicationHelper

  def settings
    @app = current_tenant
  end

  def javascript
    @app = current_tenant
    @intercom_settings = []
     if params[:intercom_settings].present?
      permit_params(params)
      @intercom_settings = parse_settings(params[:intercom_settings])
    end
  end

  def render_settings
    permit_params(params)
    @cda_count = params[:value].to_i
    render :partial => 'cda_form'
  end

  def intercom_settings
    permit_params(params)
    @intercom_settings = parse_settings(params[:intercom_settings])
    validate_settings(@intercom_settings)
    redirect_to admin_javascript_path(:intercom_settings => @intercom_settings)
  end

  private def authorize
      @app = current_tenant
      unless current_admin && current_admin.id == @app.admin_id
        redirect_to root_path
        flash[:error] = "You do not have permission to access that page"
      end
    end

  private def permit_params(params)
    return params.permit(:value) if params[:value].present?
    params[:intercom_settings].each do |param|
      param.permit(:field, :value, :type)
    end
  end

  private def parse_settings(params_array)
    params_array.map { |settings| {field: settings[:field], value: settings[:value], type: settings[:type] } }
  end

  private def validate_settings(settings_array)
    settings_array.each do |hash|
      valid_attribute = false
       if hash[:type] == "date"
        valid_attribute = valid_timestamp?(hash[:value])
      elsif hash[:type ] == "integer"
        valid_attribute = valid_integer?(hash[:value])
      elsif hash[:type] == "string"
        valid_attribute = valid_string?(hash[:value])
      else
        valid_attribute = valid_float?(hash[:value])
      end
      hash[:valid_attribute?] = valid_attribute
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  set_current_tenant_by_subdomain(:app, :subdomain)
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  layout :resolve_layout

  def index
    @apps = current_admin.apps.all
  end

  def show
  end

  def new
    @app = App.new
  end

  def create
    @app = current_admin.apps.new(app_params)
    if @app.save
      redirect_to root_url(subdomain: @app.subdomain)
    else
      render 'new'
    end
  end

  def update
    @app = current_tenant
    if @app.update(app_params)
      redirect_to request.referrer
      flash[:success] = "Settings updated"
    else
      render "/admin/pages/settings"
    end
  end

  def destroy
    App.find(current_tenant.id).destroy
    flash[:success] = "App deleted"
    redirect_to root_url(:subdomain => false)
  end

  private
    def app_params
      params.require(:app).permit(:intercom_id, :subdomain, :user_id_enabled, :secure_mode_enabled)
    end

    def resolve_layout
      if action_name == 'show'
        'apps_layout'
      elsif action_name == 'update'
        'admin_layout'
      else
        'application'
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_admin && current_admin.apps.none?
      redirect_to '/apps/new'
    elsif current_admin && current_admin.apps.any?
      redirect_to '/apps'
    else
      redirect_to '/admins/sign_in'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-warning"
    end
  end

  def intercom_settings
    if current_tenant
      if current_user
        jsify(logged_in_string(current_user))
      elsif current_admin
        jsify(logged_in_string(current_admin))
      else
        jsify(logged_out_string)
      end
    end
  end

  def jsify(string)
    javascript_tag(string)
  end

  def logged_out_string
    "window.intercomSettings = {
          app_id: '#{current_tenant.intercom_id}'
        };"
  end

  def logged_in_string(user)
    "window.intercomSettings = { #{get_custom_settings}
        app_id: '#{current_tenant.intercom_id}',
        email: '#{user.email}',
        created_at: #{user.created_at.to_i}
      };"
  end

  def get_custom_settings(cdas=[])
    settings = ""
    settings += get_user_id if user_id_enabled?
    settings
  end

  def get_user_id
      return "
        user_id: 'user_#{current_user.id}'," if current_user
      return "
        user_id: 'admin_#{current_admin.id}'," if current_admin
  end

  def user_id_enabled?
    current_tenant.user_id_enabled?
  end
end

app/views/admin/pages/_admin_javascript_settings.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#logged_in" aria-controls="home" role="tab" data-toggle="tab">Logged in snippet</a>
  </li>
  <li role="presentation">
    <a href="#logged_out" aria-controls="profile" role="tab" data-toggle="tab">Logged out snippet</a>
  </li>
</ul>
<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="logged_in">
    <pre>
      <code>
        <%= logged_in_string(current_admin, @intercom_settings) %>
      </code></pre>
  </div>
  <div  role="tabpanel" class="tab-pane" id="logged_out">
    <pre>
      <code>
        <%= logged_out_string %>
      </code></pre>
  </div>
</div>

app/views/admin/pages/_cda_count_form.html.erb
<form id="cda_count_form">
<label>Number of Custom Attributes to Create</label>
<select id="cda_count" name="cda count">
  <% n = 1 %>
  <% 5.times do %>
    <option value="count"><%= n %></option>
    <% n += 1 %>
  <% end %>
</select>
<input type="submit" value="Submit">
</form>

app/views/admin/pages/_cda_form.html.erb
<form action='/admin/intercom_settings' method="POST">
<%= token_tag %>
  <% @cda_count.times do %>
    <fieldset>
        <label style="font-weight:normal">Attribute Name</label>
        <input ... name="intercom_settings[][field]"/>
        <label style="font-weight:normal">Value</label>
        <input ... name="intercom_settings[][value]" />
        <label style="font-weight:normal">Data Type</label>
        <select name="intercom_settings[][type]">
          <option value="date">Date</option>
          <option value="string">String</option>
          <option value="float">Float</option>
          <option value="integer">Integer</option>
        </select>
    </fieldset>
  <% end %>
  <input type="submit"/>
</form>

app/views/admin/pages/javascript.html.erb
<div class="admin-main-wrapper">
  <div class="settings-wrapper">
    <div class="settings-card">
      <p class="title">Javascript Settings</p>
      <%= form_for @app do |f| %>
        <% if @app.errors.any? %>
          <p>
            Looks like something went wrong. Fix the following and try again.
          </p>
          <ul>
            <% @app.errors.each do |attribute, message| %>
              <li class="error">
                <%= attribute %> <%= message %>
              </li>
            <% end %>
          </ul>
        <% end %>
        <div class="checkbox">
          <label>
            <%= f.check_box :user_id_enabled %> Include user_id
          </label>
        </div>
        <br>
        <%= f.submit "Save", class: "submit" %>
      <% end %>
    </div>
    <div class="settings-card">
      <p class="title">Your Javascript Snippet</p>
      <p>The javascript below uses your admin details. On your site, intercomSettings will change according to the account you are logged in with at the time.</p>
      <%= render '/admin/pages/admin_javascript_settings' %>
      <%= render '/admin/pages/cda_count_form' %>
    </div>
  </div>
</div>

app/views/admin/pages/settings.html.erb
<div class="admin-main-wrapper">
  <div class="settings-wrapper">
    <div class="settings-card">
      <p class="title">Basic Settings</p>
      <%= form_for @app do |f| %>
        <% if @app.errors.any? %>
          <p>
            Looks like something went wrong. Fix the following and try again.
          </p>
          <ul>
            <% @app.errors.each do |attribute, message| %>
              <li class="error">
                <%= attribute %> <%= message %>
              </li>
            <% end %>
          </ul>
        <% end %>
        <div class="form-group">
          <%= f.label :intercom_id, "Intercom app id" %>
          <%= f.text_field :intercom_id, class: "form-control"%><br />
        </div>
        <div class="form-group">
          <%= f.label :subdomain, "Subdomain" %>
          <%= f.text_field :subdomain, class: "form-control"%><br />
        </div>
        <br>
        <%= f.submit "Save", class: "submit" %>
      <% end %>
    </div>
    <div class="settings-card">
      <%= link_to "Delete", @app, method: :delete, data: {confirm: "This will destroy the current site. Are you sure?"}, class: "delete" %>
    </div>
  </div>
</div>

app/views/admin/shared/_admin_javascript_settings.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#logged_in" aria-controls="home" role="tab" data-toggle="tab">Logged in snippet</a>
  </li>
  <li role="presentation">
    <a href="#logged_out" aria-controls="profile" role="tab" data-toggle="tab">Logged out snippet</a>
  </li>
</ul>
<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="logged_in">
    <pre>
      <code>
        <%= logged_in_string(current_admin) %>
      </code></pre>
  </div>
  <div  role="tabpanel" class="tab-pane" id="logged_out">
    <pre>
      <code>
        <%= logged_out_string %>
      </code></pre>
  </div>
</div>

app/views/admin/shared/_header.html.erb
<header class="navbar navbar-default" id="admin-nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Intermap</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_admin %>
        <% if current_tenant %>
          <li>
            <%= link_to 'My sites', root_url(:subdomain => false) %>
          </li>
          <li>
            <%= link_to 'Go to site', '/', :target => "_blank" %>
          </li>
        <% end %>
        <li>
          <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/admin/shared/_sidebar.html.erb
<div class="admin-sidebar">
  <ul class="sidebar">
    <li>
      <a href="/admin/settings">
        <i class="fa fa-cogs" aria-hidden="true"></i>
        Settings
      </a>
    </li>
    <li>
      <a href="/admin/javascript">
        <i class="fa fa-code" aria-hidden="true"></i>
        Javascript
      </a>
    </li>
    <li>
      <a href="/admins/edit">
        <i class="fa fa-user" aria-hidden="true"></i>
        Account
      </a>
    </li>
  </ul>
</div>

app/views/apps/index.html.erb
<div class="container app-list-container">
  <div class="row app-list-row">
    <h3>Your Sites</h3>
    <ul class="app-list">
      <% @apps.each do |app| %>
        <li>
          <a href="<%= root_url(subdomain: app.subdomain) %>" class="app-card">
            <p class="app-subdomain">
              <%= app.subdomain %>
            </p>
            <p class="app-id">
              <%= app.intercom_id %>
            </p>
          </a>
        </li>
      <% end %>
      <li>
        <a href="<%= new_app_path %>" class="app-card">
          <p class="app-subdomain">
            Add a new site
          </p>
          <i class="glyphicon glyphicon-plus"></i>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/apps/new.html.erb
<div class="apps-main-wrapper">
  <div class="settings-wrapper">
    <div class="settings-card">
      <p class="title">Create a new app</p>
      <%= form_for @app do |f| %>
        <% if @app.errors.any? %>
          <p>
            Looks like something went wrong. Fix the following and try again.
          </p>
          <ul>
            <% @app.errors.each do |attribute, message| %>
              <li class="error">
                <%= attribute %> <%= message %>
              </li>
            <% end %>
          </ul>
        <% end %>
        <div class="form-group">
          <%= f.label :intercom_id, "Intercom app id" %>
          <%= f.text_field :intercom_id, class: "form-control"%><br />
        </div>
        <div class="form-group">
          <%= f.label :subdomain, "Subdomain" %>
          <%= f.text_field :subdomain, class: "form-control"%><br />
        </div>
        <br>
        <%= f.submit "Create", class: "submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/apps/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Intermap</h1>
                    <hr class="small">
                    <span class="subheading">
                      <%= current_tenant.subdomain %>
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-preview">
                <a href="#">
                    <h2 class="post-title">
                        Man must explore, and this is exploration at its greatest
                    </h2>
                    <h3 class="post-subtitle">
                        Problems look mighty small from 150 miles up
                    </h3>
                </a>
                <p class="post-meta">Posted on September 24, 2016</p>
            </div>
            <hr>
            <div class="post-preview">
                <a href="#">
                    <h2 class="post-title">
                        I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                    </h2>
                </a>
                <p class="post-meta">Posted on September 18, 2016</p>
            </div>
            <hr>
            <div class="post-preview">
                <a href="#">
                    <h2 class="post-title">
                        Science has not yet mastered prophecy
                    </h2>
                    <h3 class="post-subtitle">
                        We predict too much for the next year and yet far too little for the next ten.
                    </h3>
                </a>
                <p class="post-meta">Posted on August 24, 2016</p>
            </div>
            <hr>
            <div class="post-preview">
                <a href="#">
                    <h2 class="post-title">
                        Failure is not an option
                    </h2>
                    <h3 class="post-subtitle">
                        Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                    </h3>
                </a>
                <p class="post-meta">Posted on July 8, 2016</p>
            </div>
            <hr>
            <!-- Pager -->
            <ul class="pager">
                <li class="next">
                    <a href="#">Older Posts &rarr;</a>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intermap</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="admin-body">
  <main>
    <%= render 'shared/flash' %>
    <%= render "/admin/shared/header" %>
    <%= render '/admin/shared/sidebar' %>
    <%= yield %>
  </main>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intermap</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <main>
    <%= render 'shared/flash' %>
    <%= render "/admin/shared/header" %>
    <%= yield %>
  </main>
</body>
</html>

app/views/layouts/apps_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intermap</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/nav" %>
  <main>
    <%= render 'shared/flash' %>
    <%= yield %>
  </main>
  <%= render "shared/footer" %>
  <%= render "shared/app_javascript" %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Intermap</h1>
<% unless current_admin %>
  <%= link_to('Get Started', new_admin_registration_path)  %>
<% else %>
  <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
<% end %>

app/views/shared/_app_javascript.html.erb
<%= intercom_settings %>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/<%= current_tenant.intercom_id %>';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<hr>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if current_admin %>
                <li>
                  <%= link_to 'My sites', root_url(:subdomain => false) %>
                </li>
                <li>
                  <%= link_to 'Dashboard', admin_settings_path %>
                </li>
                <li>
                  <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
                </li>
              <% elsif user_signed_in? %>
                <li>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                </li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Login
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to 'User', new_user_session_path %>
                    </li>
                    <li>
                      <%= link_to 'Admin', new_admin_session_path %>
                    </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>